# Generated by Django 5.0.8 on 2025-03-17 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant_Management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='manager',
            field=models.OneToOneField(limit_choices_to={'user_type__name': 'RESTAURANT_ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_restaurant', to=settings.AUTH_USER_MODEL),
        ),
    ]
